# Generate new secrets with `openssl rand -hex 16`
secrets:
  enabled: true
  sessionSecret: "8D4F5F54AB64CFD1E4100CDC0DE81677"
  magicLinkSecret: "28572B7F8C459CFA8C75DE234B1ADE70"
  encryptionKey: "48614428283353dca1360cd3081794fd"
  managedWorkerSecret: "2fbdec67ed767fcac310d7aed59f2537"

# Application URLs
webapp:
  appOrigin: "http://localhost:3040"
  loginOrigin: "http://localhost:3040"
  apiOrigin: "http://localhost:3040"

  resources:
    requests:
      cpu: 500m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 2Gi

supervisor:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 1Gi
